// Auto-generated by OneDriveClassify on Saturday, March 21, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedriveaccess.model;

import com.google.gson.annotations.SerializedName;

public class ChunkedUploadSessionDescriptor {

   @SerializedName("name")
   public String Name;
   @SerializedName("size")
   public long Size;

}
