// Auto-generated by ODataClassify on Tuesday, March 10, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedriveaccess.model;

import com.google.gson.annotations.SerializedName;

public class File {

   @SerializedName("hashes")
   public Hashes Hashes;
   @SerializedName("mimeType")
   public String MimeType;

}
