// Auto-generated by ODataClassify on Tuesday, March 10, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedriveaccess.model;

import com.google.gson.annotations.SerializedName;

public class SharingLink {

   @SerializedName("application")
   public Identity Application;
   @SerializedName("token")
   public String Token;
   @SerializedName("type")
   public String Type;
   @SerializedName("webUrl")
   public String WebUrl;

}
