// Auto-generated by ODataClassify on Tuesday, March 10, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedrivesdk.model;

import com.google.gson.annotations.SerializedName;

public class Audio {

   @SerializedName("album")
   public String Album;
   @SerializedName("albumArtist")
   public String AlbumArtist;
   @SerializedName("artist")
   public String Artist;
   @SerializedName("bitrate")
   public long Bitrate;
   @SerializedName("composers")
   public String Composers;
   @SerializedName("copyright")
   public String Copyright;
   @SerializedName("disc")
   public int Disc;
   @SerializedName("discCount")
   public int DiscCount;
   @SerializedName("duration")
   public long Duration;
   @SerializedName("genre")
   public String Genre;
   @SerializedName("hasDrm")
   public boolean HasDrm;
   @SerializedName("isVariableBitrate")
   public boolean IsVariableBitrate;
   @SerializedName("title")
   public String Title;
   @SerializedName("track")
   public long Track;
   @SerializedName("trackCount")
   public long TrackCount;
   @SerializedName("year")
   public long Year;

}
