// Auto-generated by ODataClassify on Tuesday, March 10, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedrivesdk.model;

import com.google.gson.annotations.SerializedName;

public class IdentitySet {

   @SerializedName("application")
   public Identity Application;
   @SerializedName("device")
   public Identity Device;
   @SerializedName("user")
   public Identity User;

}
