// Auto-generated by ODataClassify on Tuesday, March 10, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedrivesdk.model;

import com.google.gson.annotations.SerializedName;

public class Location {

   @SerializedName("altitude")
   public double Altitude;
   @SerializedName("latitude")
   public double Latitude;
   @SerializedName("longitude")
   public double Longitude;

}
