// Auto-generated by ODataClassify on Tuesday, March 10, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedrivesdk.model;

import com.google.gson.annotations.SerializedName;
import java.util.Date;

public class Photo {

   @SerializedName("cameraMake")
   public String CameraMake;
   @SerializedName("cameraModel")
   public String CameraModel;
   @SerializedName("exposureDenominator")
   public double ExposureDenominator;
   @SerializedName("exposureNumerator")
   public double ExposureNumerator;
   @SerializedName("focalLength")
   public double FocalLength;
   @SerializedName("fNumber")
   public double FNumber;
   @SerializedName("takenDateTime")
   public Date TakenDateTime;

}
