// Auto-generated by ODataClassify on Tuesday, March 10, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedrivesdk.model;

import com.google.gson.annotations.SerializedName;

public class Quota {

   @SerializedName("deleted")
   public long Deleted;
   @SerializedName("remaining")
   public long Remaining;
   @SerializedName("state")
   public String State;
   @SerializedName("total")
   public long Total;
   @SerializedName("used")
   public long Used;

}
