// Auto-generated by ODataClassify on Tuesday, March 10, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedrivesdk.model;

import com.google.gson.annotations.SerializedName;

public class SharingInvitation {

   @SerializedName("email")
   public String Email;
   @SerializedName("redeemedBy")
   public String RedeemedBy;
   @SerializedName("signInRequired")
   public boolean SignInRequired;

}
