// Auto-generated by ODataClassify on Tuesday, March 10, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package com.microsoft.onedrivesdk.model;

import com.google.gson.annotations.SerializedName;

public class Video {

   @SerializedName("bitrate")
   public long Bitrate;
   @SerializedName("duration")
   public long Duration;
   @SerializedName("height")
   public long Height;
   @SerializedName("width")
   public long Width;

}
